<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\User' . "\0" . 'apellidos', '' . "\0" . 'App\\Entity\\User' . "\0" . 'bloqueado', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dni', '' . "\0" . 'App\\Entity\\User' . "\0" . 'fnacimiento', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lnacimiento', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\User' . "\0" . 'estCivil', '' . "\0" . 'App\\Entity\\User' . "\0" . 'permConducir', '' . "\0" . 'App\\Entity\\User' . "\0" . 'vehiProp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'vehiEmp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\User' . "\0" . 'jornada', '' . "\0" . 'App\\Entity\\User' . "\0" . 'departamentos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\User' . "\0" . 'apellidos', '' . "\0" . 'App\\Entity\\User' . "\0" . 'bloqueado', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dni', '' . "\0" . 'App\\Entity\\User' . "\0" . 'fnacimiento', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lnacimiento', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nacionalidad', '' . "\0" . 'App\\Entity\\User' . "\0" . 'estCivil', '' . "\0" . 'App\\Entity\\User' . "\0" . 'permConducir', '' . "\0" . 'App\\Entity\\User' . "\0" . 'vehiProp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'vehiEmp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\User' . "\0" . 'jornada', '' . "\0" . 'App\\Entity\\User' . "\0" . 'departamentos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos(string $apellidos): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getBloqueado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloqueado', []);

        return parent::getBloqueado();
    }

    /**
     * {@inheritDoc}
     */
    public function setBloqueado(?bool $bloqueado): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBloqueado', [$bloqueado]);

        return parent::setBloqueado($bloqueado);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', []);

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni(string $dni): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', [$dni]);

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getFnacimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFnacimiento', []);

        return parent::getFnacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFnacimiento(?\DateTimeInterface $fnacimiento): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFnacimiento', [$fnacimiento]);

        return parent::setFnacimiento($fnacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getLnacimiento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLnacimiento', []);

        return parent::getLnacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setLnacimiento(?string $lnacimiento): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLnacimiento', [$lnacimiento]);

        return parent::setLnacimiento($lnacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo(?string $sexo): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidad', []);

        return parent::getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidad(?string $nacionalidad): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidad', [$nacionalidad]);

        return parent::setNacionalidad($nacionalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstCivil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstCivil', []);

        return parent::getEstCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstCivil(?string $estCivil): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstCivil', [$estCivil]);

        return parent::setEstCivil($estCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermConducir(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermConducir', []);

        return parent::getPermConducir();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermConducir(?string $permConducir): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermConducir', [$permConducir]);

        return parent::setPermConducir($permConducir);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiProp(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiProp', []);

        return parent::getVehiProp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiProp(?bool $vehiProp): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiProp', [$vehiProp]);

        return parent::setVehiProp($vehiProp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiEmp(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiEmp', []);

        return parent::getVehiEmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiEmp(?bool $vehiEmp): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiEmp', [$vehiEmp]);

        return parent::setVehiEmp($vehiEmp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(?string $telefono): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getJornada(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJornada', []);

        return parent::getJornada();
    }

    /**
     * {@inheritDoc}
     */
    public function addJornada(\App\Entity\Jornada $jornada): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJornada', [$jornada]);

        return parent::addJornada($jornada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJornada(\App\Entity\Jornada $jornada): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJornada', [$jornada]);

        return parent::removeJornada($jornada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamentos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamentos', []);

        return parent::getDepartamentos();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepartamento(\App\Entity\Departamentos $departamento): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepartamento', [$departamento]);

        return parent::addDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepartamento(\App\Entity\Departamentos $departamento): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepartamento', [$departamento]);

        return parent::removeDepartamento($departamento);
    }

}
