<?php

namespace App\Form;

use App\Entity\Alumnos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AlumnosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre', TextType::class, [
                        'label'    => 'Nombre',
                    ])
            ->add('apellidos', TextType::class, [
                        'label'    => 'Apellidos',
                    ])
            ->add('email', EmailType::class, [
                        'label'    => 'Email',
                    ])
            ->add('telefono', TextType::class, [
                        'label'    => 'Teléfono',
                    ])
            ->add('ident', TextType::class, [
                        'label'    => 'DNI/NIE/NIF/Pasaporte',
                    ])
            ->add('direccion', TextareaType::class, [
                        'label'    => 'Dirección',
                    ])
            ->add('localidad', TextType::class, [
                        'label'    => 'Localidad',
                    ])
            ->add('provincia', TextType::class, [
                        'label'    => 'Provincia',
                    ])
            ->add('pais', ChoiceType::class, [
                        'label'    => 'Pais',
                        'choices' => [
                            'Afganistan' => 'Afganistan',
                            'Albania' => 'Albania',
                            'Alemania' => 'Alemania',
                            'Andorra' => 'Andorra',
                            'Angola' => 'Angola',
                            'Anguilla' => 'Anguilla',
                            'Antigua Y Barbuda' => 'Antigua Y Barbuda',
                            'Antillas Holandesas' => 'Antillas Holandesas',
                            'Arabia Saudi' => 'Arabia Saudi',
                            'Argelia' => 'Argelia',
                            'Argentina' => 'Argentina',
                            'Armenia' => 'Armenia',
                            'Aruba' => 'Aruba',
                            'Australia' => 'Australia',
                            'Austria' => 'Austria',
                            'Azerbaiyan' => 'Azerbaiyan',
                            'Bahamas' => 'Bahamas',
                            'Bahrein' => 'Bahrein',
                            'Bangladesh' => 'Bangladesh',
                            'Barbados' => 'Barbados',
                            'Belarus' => 'Belarus',
                            'Belgica' => 'Belgica',
                            'Belice' => 'Belice',
                            'Benin' => 'Benin',
                            'Bermudas' => 'Bermudas',
                            'Bhután' => 'Bhután',
                            'Bolivia' => 'Bolivia',
                            'Bosnia Y Herzegovina' => 'Bosnia Y Herzegovina',
                            'Botswana' => 'Botswana',
                            'Brasil' => 'Brasil',
                            'Brunei' => 'Brunei',
                            'Bulgaria' => 'Bulgaria',
                            'Burkina Faso' => 'Burkina Faso',
                            'Burundi' => 'Burundi',
                            'Cabo Verde' => 'Cabo Verde',
                            'Camboya' => 'Camboya',
                            'Camerun' => 'Camerun',
                            'Canada' => 'Canada',
                            'Chad' => 'Chad',
                            'Chile' => 'Chile',
                            'China' => 'China',
                            'Chipre' => 'Chipre',
                            'Colombia' => 'Colombia',
                            'Comores' => 'Comores',
                            'Congo' => 'Congo',
                            'Corea' => 'Corea',
                            'Corea Del Norte ' => 'Corea Del Norte ',
                            'Costa De Marfil' => 'Costa De Marfil',
                            'Costa Rica' => 'Costa Rica',
                            'Croacia' => 'Croacia',
                            'Cuba' => 'Cuba',
                            'Dinamarca' => 'Dinamarca',
                            'Djibouti' => 'Djibouti',
                            'Dominica' => 'Dominica',
                            'Ecuador' => 'Ecuador',
                            'Egipto' => 'Egipto',
                            'El Salvador' => 'El Salvador',
                            'Emiratos Arabes Unidos' => 'Emiratos Arabes Unidos',
                            'Eritrea' => 'Eritrea',
                            'Eslovenia' => 'Eslovenia',
                            'España' => 'España',
                            'Estados Unidos De America' => 'Estados Unidos De America',
                            'Estonia' => 'Estonia',
                            'Etiopia' => 'Etiopia',
                            'Fiji' => 'Fiji',
                            'Filipinas' => 'Filipinas',
                            'Finlandia' => 'Finlandia',
                            'Francia' => 'Francia',
                            'Gabon' => 'Gabon',
                            'Gambia' => 'Gambia',
                            'Georgia' => 'Georgia',
                            'Ghana' => 'Ghana',
                            'Gibraltar' => 'Gibraltar',
                            'Granada' => 'Granada',
                            'Grecia' => 'Grecia',
                            'Groenlandia' => 'Groenlandia',
                            'Guadalupe' => 'Guadalupe',
                            'Guam' => 'Guam',
                            'Guatemala' => 'Guatemala',
                            'Guayana Francesa' => 'Guayana Francesa',
                            'Guernesey' => 'Guernesey',
                            'Guinea' => 'Guinea',
                            'Guinea Ecuatorial' => 'Guinea Ecuatorial',
                            'Guinea-Bissau' => 'Guinea-Bissau',
                            'Guyana' => 'Guyana',
                            'Haiti' => 'Haiti',
                            'Honduras' => 'Honduras',
                            'Hong Kong' => 'Hong Kong',
                            'Hungria' => 'Hungria',
                            'India' => 'India',
                            'Indonesia' => 'Indonesia',
                            'Iran' => 'Iran',
                            'Iraq' => 'Iraq',
                            'Irlanda' => 'Irlanda',
                            'Isla De Man' => 'Isla De Man',
                            'Isla Norfolk' => 'Isla Norfolk',
                            'Islandia' => 'Islandia',
                            'Islas Aland' => 'Islas Aland',
                            'Islas Caimán' => 'Islas Caimán',
                            'Islas Cook' => 'Islas Cook',
                            'Islas Del Canal' => 'Islas Del Canal',
                            'Islas Feroe' => 'Islas Feroe',
                            'Islas Malvinas' => 'Islas Malvinas',
                            'Islas Marianas Del Norte' => 'Islas Marianas Del Norte',
                            'Islas Marshall' => 'Islas Marshall',
                            'Islas Pitcairn' => 'Islas Pitcairn',
                            'Islas Salomon' => 'Islas Salomon',
                            'Islas Turcas Y Caicos' => 'Islas Turcas Y Caicos',
                            'Islas Virgenes Britanicas' => 'Islas Virgenes Britanicas',
                            'Islas Vírgenes De Los Estados Unidos' => 'Islas Vírgenes De Los Estados Unidos',
                            'Israel' => 'Israel',
                            'Italia' => 'Italia',
                            'Jamaica' => 'Jamaica',
                            'Japon' => 'Japon',
                            'Jersey' => 'Jersey',
                            'Jordania' => 'Jordania',
                            'Kazajstan' => 'Kazajstan',
                            'Kenia' => 'Kenia',
                            'Kirguistan' => 'Kirguistan',
                            'Kiribati' => 'Kiribati',
                            'Kuwait' => 'Kuwait',
                            'Laos' => 'Laos',
                            'Lesotho' => 'Lesotho',
                            'Letonia' => 'Letonia',
                            'Libano' => 'Libano',
                            'Liberia' => 'Liberia',
                            'Libia' => 'Libia',
                            'Liechtenstein' => 'Liechtenstein',
                            'Lituania' => 'Lituania',
                            'Luxemburgo' => 'Luxemburgo',
                            'Macao' => 'Macao',
                            'Macedonia ' => 'Macedonia ',
                            'Madagascar' => 'Madagascar',
                            'Malasia' => 'Malasia',
                            'Malawi' => 'Malawi',
                            'Maldivas' => 'Maldivas',
                            'Mali' => 'Mali',
                            'Malta' => 'Malta',
                            'Marruecos' => 'Marruecos',
                            'Martinica' => 'Martinica',
                            'Mauricio' => 'Mauricio',
                            'Mauritania' => 'Mauritania',
                            'Mayotte' => 'Mayotte',
                            'Mexico' => 'Mexico',
                            'Micronesia' => 'Micronesia',
                            'Moldavia' => 'Moldavia',
                            'Monaco' => 'Monaco',
                            'Mongolia' => 'Mongolia',
                            'Montenegro' => 'Montenegro',
                            'Montserrat' => 'Montserrat',
                            'Mozambique' => 'Mozambique',
                            'Myanmar' => 'Myanmar',
                            'Namibia' => 'Namibia',
                            'Nauru' => 'Nauru',
                            'Nepal' => 'Nepal',
                            'Nicaragua' => 'Nicaragua',
                            'Niger' => 'Niger',
                            'Nigeria' => 'Nigeria',
                            'Niue' => 'Niue',
                            'Noruega' => 'Noruega',
                            'Nueva Caledonia' => 'Nueva Caledonia',
                            'Nueva Zelanda' => 'Nueva Zelanda',
                            'Oman' => 'Oman',
                            'Paises Bajos' => 'Paises Bajos',
                            'Pakistan' => 'Pakistan',
                            'Palaos' => 'Palaos',
                            'Palestina' => 'Palestina',
                            'Panama' => 'Panama',
                            'Papua Nueva Guinea' => 'Papua Nueva Guinea',
                            'Paraguay' => 'Paraguay',
                            'Peru' => 'Peru',
                            'Polinesia Francesa' => 'Polinesia Francesa',
                            'Polonia' => 'Polonia',
                            'Portugal' => 'Portugal',
                            'Puerto Rico' => 'Puerto Rico',
                            'Qatar' => 'Qatar',
                            'Reino Unido' => 'Reino Unido',
                            'Rep.Democratica Del Congo' => 'Rep.Democratica Del Congo',
                            'Republica Centroafricana' => 'Republica Centroafricana',
                            'Republica Checa' => 'Republica Checa',
                            'Republica Dominicana' => 'Republica Dominicana',
                            'Republica Eslovaca' => 'Republica Eslovaca',
                            'Reunion' => 'Reunion',
                            'Ruanda' => 'Ruanda',
                            'Rumania' => 'Rumania',
                            'Rusia' => 'Rusia',
                            'Sahara Occidental' => 'Sahara Occidental',
                            'Samoa' => 'Samoa',
                            'Samoa Americana' => 'Samoa Americana',
                            'San Bartolome' => 'San Bartolome',
                            'San Cristobal Y Nieves' => 'San Cristobal Y Nieves',
                            'San Marino' => 'San Marino',
                            'San Martin (Parte Francesa)' => 'San Martin (Parte Francesa)',
                            'San Pedro Y Miquelon ' => 'San Pedro Y Miquelon ',
                            'San Vicente Y Las Granadinas' => 'San Vicente Y Las Granadinas',
                            'Santa Helena' => 'Santa Helena',
                            'Santa Lucia' => 'Santa Lucia',
                            'Santa Sede' => 'Santa Sede',
                            'Santo Tome Y Principe' => 'Santo Tome Y Principe',
                            'Senegal' => 'Senegal',
                            'Serbia' => 'Serbia',
                            'Seychelles' => 'Seychelles',
                            'Sierra Leona' => 'Sierra Leona',
                            'Singapur' => 'Singapur',
                            'Siria' => 'Siria',
                            'Somalia' => 'Somalia',
                            'Sri Lanka' => 'Sri Lanka',
                            'Sudafrica' => 'Sudafrica',
                            'Sudan' => 'Sudan',
                            'Suecia' => 'Suecia',
                            'Suiza' => 'Suiza',
                            'Surinam' => 'Surinam',
                            'Svalbard Y Jan Mayen' => 'Svalbard Y Jan Mayen',
                            'Swazilandia' => 'Swazilandia',
                            'Tadyikistan' => 'Tadyikistan',
                            'Tailandia' => 'Tailandia',
                            'Tanzania' => 'Tanzania',
                            'Timor Oriental' => 'Timor Oriental',
                            'Togo' => 'Togo',
                            'Tokelau' => 'Tokelau',
                            'Tonga' => 'Tonga',
                            'Trinidad Y Tobago' => 'Trinidad Y Tobago',
                            'Tunez' => 'Tunez',
                            'Turkmenistan' => 'Turkmenistan',
                            'Turquia' => 'Turquia',
                            'Tuvalu' => 'Tuvalu',
                            'Ucrania' => 'Ucrania',
                            'Uganda' => 'Uganda',
                            'Uruguay' => 'Uruguay',
                            'Uzbekistan' => 'Uzbekistan',
                            'Vanuatu' => 'Vanuatu',
                            'Venezuela' => 'Venezuela',
                            'Vietnam' => 'Vietnam',
                            'Wallis Y Fortuna' => 'Wallis Y Fortuna',
                            'Yemen' => 'Yemen',
                            'Zambia' => 'Zambia',
                            'Zimbabwe' => 'Zimbabwe',
                        ],
                    ])
            ->add('fnacimiento', BirthdayType::class, [
                        'label'    => 'Fecha de Nacimiento',
                        'widget'   => 'single_text',
                        'required' => false,
                    ])
            ->add('Guardar', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Alumnos::class,
        ]);
    }
}
