<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK9x9YnE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK9x9YnE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK9x9YnE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK9x9YnE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK9x9YnE\App_KernelDevDebugContainer([
    'container.build_hash' => 'K9x9YnE',
    'container.build_id' => '4ddbc299',
    'container.build_time' => 1668168123,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK9x9YnE');
