<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.f799512a.js',
                '/build/758.ca289d08.js',
                '/build/app.3bb5a12a.js',
            ],
            'css' => [
                '/build/app.b75294ae.css',
            ],
        ],
    ],
],

]];
